//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXCEL2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AP__DocIntegratedDataStorage
    {
        public int ID { get; set; }
        public int CreatorId { get; set; }
        public System.DateTime Created { get; set; }
        public int CreatorType { get; set; }
        public int ModifierId { get; set; }
        public System.DateTime Modified { get; set; }
        public int ModifierType { get; set; }
        public int AscDocId { get; set; }
        public byte[] Content { get; set; }
    }
}
