//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXCEL2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AP__DocIntegratedStorage
    {
        public int ID { get; set; }
        public int CreatorId { get; set; }
        public System.DateTime Created { get; set; }
        public int CreatorType { get; set; }
        public int ModifierId { get; set; }
        public System.DateTime Modified { get; set; }
        public int ModifierType { get; set; }
        public int IntegrationObject { get; set; }
        public int IntegrationObjectId { get; set; }
        public int AscTermId { get; set; }
        public int SourceIntegration { get; set; }
        public string Name { get; set; }
        public string Extension { get; set; }
        public long Weight { get; set; }
        public int Version { get; set; }
        public System.Guid GUID { get; set; }
        public string Description { get; set; }
        public int RecordId { get; set; }
        public bool IntegrateLibrary { get; set; }
        public int ObjectTypeProcess { get; set; }
        public int ObjectTypeProcessId { get; set; }
        public int ObjectTypeProcessLog { get; set; }
        public int ObjectTypeProcessLogId { get; set; }
        public int AscDocStorageId { get; set; }
        public string C_Txt1 { get; set; }
        public string C_Txt2 { get; set; }
        public string C_Txt3 { get; set; }
        public string C_Txt4 { get; set; }
        public string C_Txt5 { get; set; }
        public string C_Txt6 { get; set; }
        public string C_Txt7 { get; set; }
        public string C_Txt8 { get; set; }
        public string C_Txt9 { get; set; }
        public string C_Txt10 { get; set; }
        public string C_Txt11 { get; set; }
        public string C_Txt12 { get; set; }
        public string C_Txt13 { get; set; }
        public string C_Txt14 { get; set; }
        public string C_Txt15 { get; set; }
        public string C_Txt16 { get; set; }
        public int AscDocStorage_SubFolderId { get; set; }
        public int Height { get; set; }
        public int Width { get; set; }
        public string C_Txt17 { get; set; }
        public string C_Txt18 { get; set; }
        public string C_Txt19 { get; set; }
        public string C_Txt20 { get; set; }
        public string C_Txt21 { get; set; }
        public string C_Txt22 { get; set; }
        public string C_Txt23 { get; set; }
        public string C_Txt24 { get; set; }
        public string C_Txt25 { get; set; }
        public string C_Txt26 { get; set; }
        public string C_Txt27 { get; set; }
        public string C_Txt28 { get; set; }
        public string C_Txt29 { get; set; }
        public string C_Txt30 { get; set; }
        public string C_Txt31 { get; set; }
        public string C_Txt32 { get; set; }
        public string C_Txt_Multi1 { get; set; }
        public string C_Txt_Multi2 { get; set; }
        public string C_Txt_Multi3 { get; set; }
        public string C_Txt_Multi4 { get; set; }
        public string C_Txt_Multi5 { get; set; }
        public string C_Txt_Multi6 { get; set; }
        public string C_Txt_Multi7 { get; set; }
        public string C_Txt_Multi8 { get; set; }
        public string Token { get; set; }
        public int Upload { get; set; }
    }
}
