//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXCEL2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AP_Dyn_Familias_27
    {
        public int ID { get; set; }
        public Nullable<int> C_ElementID { get; set; }
        public Nullable<System.DateTime> Creado { get; set; }
        public Nullable<int> IdCreador { get; set; }
        public Nullable<int> TipoCreador { get; set; }
        public Nullable<System.DateTime> Modificado { get; set; }
        public Nullable<int> IdModificador { get; set; }
        public Nullable<int> TipoModificador { get; set; }
        public Nullable<int> C_FamilyClass { get; set; }
        public string C_Name { get; set; }
        public Nullable<int> C_FamilyRecord_Priority { get; set; }
        public Nullable<int> C_FamilyRecord_Status { get; set; }
        public string C_FamilyRecord_Description { get; set; }
        public Nullable<System.DateTime> C_FamilyRecord_From { get; set; }
        public Nullable<System.DateTime> C_FamilyRecord_To { get; set; }
        public Nullable<int> C_SecureRoomID { get; set; }
    }
}
