//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXCEL2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AuraPortal_BPMSEntities : DbContext
    {
        public AuraPortal_BPMSEntities()
            : base("name=AuraPortal_BPMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Panel_5_2664> Panel_5_2664 { get; set; }
        public virtual DbSet<Panel_5> Panel_5 { get; set; }
        public virtual DbSet<Panel_1008> Panel_1008 { get; set; }
        public virtual DbSet<Panel_1008_4700> Panel_1008_4700 { get; set; }
        public virtual DbSet<AP__DocIntegratedDataStorage> AP__DocIntegratedDataStorage { get; set; }
        public virtual DbSet<AP_Dyn_Familias_26> AP_Dyn_Familias_26 { get; set; }
        public virtual DbSet<AP__DocIntegratedStorage> AP__DocIntegratedStorage { get; set; }
        public virtual DbSet<AP_Dyn_Familias_27> AP_Dyn_Familias_27 { get; set; }
        public virtual DbSet<Panel_1009> Panel_1009 { get; set; }
        public virtual DbSet<Panel_1009_4916> Panel_1009_4916 { get; set; }
        public virtual DbSet<AP_Dyn_Familias_30> AP_Dyn_Familias_30 { get; set; }
        public virtual DbSet<Panel_1008_7074> Panel_1008_7074 { get; set; }
        public virtual DbSet<Panel_1008_4170> Panel_1008_4170 { get; set; }
        public virtual DbSet<Panel_1008_4450> Panel_1008_4450 { get; set; }
        public virtual DbSet<Panel_1008_4233> Panel_1008_4233 { get; set; }
        public virtual DbSet<Panel_1008_4261> Panel_1008_4261 { get; set; }
        public virtual DbSet<AP_Dyn_Familias_31> AP_Dyn_Familias_31 { get; set; }
        public virtual DbSet<Panel_2011> Panel_2011 { get; set; }
        public virtual DbSet<Panel_2011_8800> Panel_2011_8800 { get; set; }
        public virtual DbSet<Panel_2011_8882> Panel_2011_8882 { get; set; }
    
        public virtual ObjectResult<PROCEDURE_GENERATE_EXCEL_Result> PROCEDURE_GENERATE_EXCEL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROCEDURE_GENERATE_EXCEL_Result>("PROCEDURE_GENERATE_EXCEL");
        }
    }
}
