//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXCEL2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Panel_2011
    {
        public int ID { get; set; }
        public Nullable<int> C_ElementID { get; set; }
        public Nullable<System.DateTime> Creado { get; set; }
        public Nullable<int> IdCreador { get; set; }
        public Nullable<int> TipoCreador { get; set; }
        public Nullable<System.DateTime> Modificado { get; set; }
        public Nullable<int> IdModificador { get; set; }
        public Nullable<int> TipoModificador { get; set; }
        public string C_List_of_Process_References { get; set; }
        public string C_List_of_Process_Themes { get; set; }
        public Nullable<System.DateTime> C3_PR3_TAG_FECHA_INICIO { get; set; }
        public string C3_PR3_TAG_REFERENCIA { get; set; }
        public Nullable<int> C3_PR3_TAG_MES { get; set; }
        public string C3_PR3_TAG_MES_TEXTO { get; set; }
        public string C3_PR3_TAG_AÑO { get; set; }
        public Nullable<int> C3_PR3_FC_IDPANEL { get; set; }
        public string C3_PR3_T_SERIE_CHILCA { get; set; }
        public string C3_PR3_T_SERIE_LIMA { get; set; }
        public string C3_PR3_T_SERIE_TRUJILLO { get; set; }
        public Nullable<int> C3_PR3_WS_WINDOWS_CORRELATIVO { get; set; }
        public Nullable<int> C8_PR3_FC_ARCHIVOS_FACTURACION_3_PR3_ARCHIVO_Cantidad_sin_fac { get; set; }
        public Nullable<int> C8_PR3_FC_ARCHIVOS_FACTURACION_3_PR3_FLAG_Cantidad_facturado { get; set; }
        public string C3_PR3_TAG_ASUNTO { get; set; }
        public string C2_PR3_FC_PRE_CORRE_LIMA_F_TAG_CORREO_PUNTO { get; set; }
        public string C2_PR3_FC_PRE_CORRE_CHILCA_F_TAG_CORREO_PUNTO { get; set; }
        public string C2_PR3_FC_PRE_CORRE_TRUJILLO_F_TAG_CORREO_PUNTO { get; set; }
        public string C3_PR3_ASUNTO1 { get; set; }
        public Nullable<int> C3_PR3_FC_ESTADO { get; set; }
        public string C3_PR3_ASUNTO_FC { get; set; }
        public Nullable<int> C8_PR3_CLIENTES_DIF_MENSUAL_3_PR3_CLI_CUENTA_Cantidad { get; set; }
    }
}
