//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXCEL2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Panel_2013_8730
    {
        public int ID { get; set; }
        public Nullable<int> C_ElementID { get; set; }
        public Nullable<System.DateTime> Creado { get; set; }
        public Nullable<int> IdCreador { get; set; }
        public Nullable<int> TipoCreador { get; set; }
        public Nullable<System.DateTime> Modificado { get; set; }
        public Nullable<int> IdModificador { get; set; }
        public Nullable<int> TipoModificador { get; set; }
        public Nullable<int> C_ExecutedScript { get; set; }
        public Nullable<int> C_Register_creation_ProcessID { get; set; }
        public Nullable<int> C_Origin_Register_ID { get; set; }
        public Nullable<int> C_RegisterStatus { get; set; }
        public Nullable<int> C_Register_Origin_ID { get; set; }
        public Nullable<int> C_Register_Origin_Type { get; set; }
        public Nullable<int> C_Numerator { get; set; }
        public string C3_PR4_TL_FECHADETRANSITO { get; set; }
        public string C3_PR4_TL_ESTACION { get; set; }
        public string C3_PR4_TL_VIA { get; set; }
        public string C3_PR4_TL_PLACA { get; set; }
        public string C3_PR4_TL_CATEGORIA { get; set; }
        public Nullable<decimal> C3_PR4_ND_VALORPEAJE { get; set; }
        public string C3_PR4_TL_FECOMPROBANTE { get; set; }
        public string C3_PR4_TL_RUCCONSECION { get; set; }
        public string C3_PR4_TL_TIPODECOMPROBANTE { get; set; }
        public string C3_PR4_TL_NUMERODECOMPROBANTE { get; set; }
        public Nullable<decimal> C3_ND_VALORDEDETRACCION { get; set; }
        public Nullable<System.DateTime> C3_FE_FECHAYHORATRANSITO_PRE { get; set; }
        public string C3_TL_NUMERODEDETRAC_PRE { get; set; }
        public Nullable<System.DateTime> C3_FE_FECHADECOMPROBANTE_PRE { get; set; }
        public string C3_PR4_TL_CONCESION { get; set; }
        public Nullable<decimal> C3_ND_SALDOCOVIPERU_PREPAGO { get; set; }
        public Nullable<decimal> C3_ND_SALDOCOVISUR_PREPAGO { get; set; }
        public Nullable<decimal> C3_ND_SALDOCOVISOL_PREPAGO { get; set; }
        public Nullable<decimal> C3_ND_CONSUDETRACCOVISO { get; set; }
        public Nullable<decimal> C3_ND_CONSUDETRACCOVISUR { get; set; }
        public Nullable<decimal> C3_ND_CONSUDETRACCOVIPERU { get; set; }
    }
}
