//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXCEL2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Panel_2011_8800
    {
        public int ID { get; set; }
        public Nullable<int> C_ElementID { get; set; }
        public Nullable<System.DateTime> Creado { get; set; }
        public Nullable<int> IdCreador { get; set; }
        public Nullable<int> TipoCreador { get; set; }
        public Nullable<System.DateTime> Modificado { get; set; }
        public Nullable<int> IdModificador { get; set; }
        public Nullable<int> TipoModificador { get; set; }
        public Nullable<int> C_ExecutedScript { get; set; }
        public Nullable<int> C_Register_creation_ProcessID { get; set; }
        public Nullable<int> C_Origin_Register_ID { get; set; }
        public Nullable<int> C_RegisterStatus { get; set; }
        public Nullable<int> C_Register_Origin_ID { get; set; }
        public Nullable<int> C_Register_Origin_Type { get; set; }
        public Nullable<int> C_Numerator { get; set; }
        public string C3_PR3_FC_CUENTA { get; set; }
        public string C3_PR3_FC_RUC { get; set; }
        public string C3_PR3_FC_RAZON_SOCIAL { get; set; }
        public string C3_PR3__FC_DIRECCION { get; set; }
        public string C3_PR3_FC_CORREO { get; set; }
        public string C3_PR3_FC_COMENTARIO2 { get; set; }
        public Nullable<decimal> C3_PR3_FC_PEAJE_COVIPERU { get; set; }
        public Nullable<decimal> C3_PR3_FC_PEAJE_COVISOL { get; set; }
        public Nullable<decimal> C3_PR3_FC_PEAJE_COVISUR { get; set; }
        public Nullable<decimal> C3_PR3_FC_TOTAL { get; set; }
        public Nullable<System.DateTime> C3_PR3_FC_FECHA_AFILIACION { get; set; }
        public Nullable<int> C3_PR3_FC_MODALIDAD { get; set; }
        public Nullable<decimal> C3_PR3_FC_ADM { get; set; }
        public Nullable<decimal> C3_PR3_FC_BASE_FAC { get; set; }
        public string C3_PR3_FC_SERIE { get; set; }
        public Nullable<int> C3_PR3_FC_DETRACCION { get; set; }
        public string C3_PR3_FC_MES_TXT { get; set; }
        public string C3_GC_FC_AÑO_TXT { get; set; }
        public Nullable<int> C3_PR3_FC_TIPO_FACT { get; set; }
        public Nullable<System.DateTime> C3_PR3_FC_FECHA_EMISION { get; set; }
        public Nullable<System.DateTime> C3_PR3_FC_FECHA_VENCIMIENTO { get; set; }
        public Nullable<int> C3_PR3_DETRACCION_SN { get; set; }
    }
}
