//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXCEL2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Panel_2013
    {
        public int ID { get; set; }
        public Nullable<int> C_ElementID { get; set; }
        public Nullable<System.DateTime> Creado { get; set; }
        public Nullable<int> IdCreador { get; set; }
        public Nullable<int> TipoCreador { get; set; }
        public Nullable<System.DateTime> Modificado { get; set; }
        public Nullable<int> IdModificador { get; set; }
        public Nullable<int> TipoModificador { get; set; }
        public string C_List_of_Process_References { get; set; }
        public string C_List_of_Process_Themes { get; set; }
        public string C8_GC_PREPAGOS_FINALES_3_PR_CORREO_ULTIMO_CORREO_PREP { get; set; }
        public string C8_GC_PREPAGOS_FINALES_3_PR_CUENTA_ULTIMA_CUENTA { get; set; }
        public Nullable<int> C8_GC_PREPAGOS_FINALES_3_PR_NE_CUENTA_ULTIMA_CUENTA_ENTERO { get; set; }
        public string C8_GC_PREPAGOS_FINALES_3_PR_EMPRESA_ULTIMA_EMPRESA_PREP { get; set; }
        public Nullable<int> C8_GC_PREPAGOS_FINALES_3_PR_PUNTODEATECION_TOTAL_DE_REGISTROS { get; set; }
        public string C8_GC_PREPAGOS_FINALES_3_PR_RUC_ULTIMO_RUC_PREPAGO { get; set; }
        public string C8_GC_PREPAGOS_FINALES_3_PR_SISTEMA_ULTIMO_SISTEMA_PREP { get; set; }
        public string C8_GC_PREPAGOS_FINALES_3_PR_TIPODEREPORTE_TIPO_DE_REPORTE_PREP { get; set; }
        public string C8_GC_POSTPAGOS_FINALES_3_PT_CORREO_ULTIMO_CORREO_POST { get; set; }
        public string C8_GC_POSTPAGOS_FINALES_3_PT_CUENTA_ULTIMA_CUENTA_POST { get; set; }
        public string C8_GC_POSTPAGOS_FINALES_3_PT_EMPRESA_ULTIMA_EMPRESA_POST { get; set; }
        public Nullable<int> C8_GC_POSTPAGOS_FINALES_3_PT_PUNTO_DE_ATENCION_TOTA_DE_REGISTROS_PO { get; set; }
        public string C8_GC_POSTPAGOS_FINALES_3_PT_RUC_ULTIMO_RUC_POST { get; set; }
        public string C8_GC_POSTPAGOS_FINALES_3_PT_SISTEMA_ULTIMO_SISTEMA_POST { get; set; }
        public string C8_GC_POSTPAGOS_FINALES_3_PT_TIPO_DE_REPORTE_TIPO_DE_REPORTE_POST { get; set; }
        public Nullable<decimal> C8_GC_CONSOLIDADODEVENTAS_3_ND_MONTOCONSOLIDADO_TOTALDEVENTAS { get; set; }
        public Nullable<decimal> C8_GC_TRANSITOGENERALESSPREPAGO_3_ND_VALORDEDETRACCION_Total_de_Detraccione { get; set; }
        public Nullable<decimal> C8_GC_TRANSITOGENERALESSPREPAGO_3_PR4_ND_VALORPEAJE_Total_del_Peaje { get; set; }
        public Nullable<int> C8_GC_TRANSITOGENERALESSPREPAGO_3_PR4_TL_ESTACION_Total_de_Peajes { get; set; }
        public Nullable<decimal> C8_GC_TRANSITOSGENERALESPOSTPAGO_3_POST_ND_VALORDETRACCION_Total_de_Detraccione { get; set; }
        public Nullable<decimal> C8_GC_TRANSITOSGENERALESPOSTPAGO_3_POST_ND_VALORPEAJE_Total_del_Peaje { get; set; }
        public Nullable<int> C8_GC_TRANSITOSGENERALESPOSTPAGO_3_POST_TL_ESTACION_Cantidad_de_Peajes { get; set; }
        public Nullable<int> C3_SS_PERIODICIDAD { get; set; }
        public Nullable<System.DateTime> C3_FE_FECHADEENVIODEREPORTES { get; set; }
        public Nullable<System.DateTime> C3_FE_FECHA_DE_INICIO_DE_PERIODO { get; set; }
        public Nullable<System.DateTime> C3_FE_FECHA_DE_FIN_DE_PERIODO { get; set; }
        public Nullable<int> C3_NE_INDICADOR { get; set; }
        public string C3_TL_REFERENCIA_PROCESO { get; set; }
        public Nullable<decimal> C8_PRE_COMPROBANTESREPORTES_3_PRE_MONTORECARGA_PRE_SUMAREGARGAS { get; set; }
        public Nullable<decimal> C8_PRE_COMPROBANTESREPORTES_3_PRE_MONTODETRACCION_PRE_SUMADETRACCIONES { get; set; }
        public Nullable<decimal> C8_PR4_GC_RECIBODECOMPROBANTES_3_POST_MONTODETRACCION_POST_ND_SUMADETRACCI { get; set; }
        public Nullable<decimal> C8_PR4_GC_RECIBODECOMPROBANTES_3_POST_MONTORECARGA_POST_ND_SUMARECARGAS { get; set; }
        public Nullable<decimal> C3_ND_SALDOCOVIPERU { get; set; }
        public Nullable<decimal> C3_ND_SALDOCOVISOL { get; set; }
        public Nullable<decimal> C3_ND_SALDOCOVISUR { get; set; }
        public Nullable<decimal> C3_ND_SALDODELULTIMOREPORTE { get; set; }
        public Nullable<decimal> C8_GC_TRANSITOGENERALESSPREPAGO_3_ND_SALDOCOVIPERU_PREPAGO_CONSUMOSCOVIPERU_PRE { get; set; }
        public Nullable<decimal> C8_GC_TRANSITOGENERALESSPREPAGO_3_ND_SALDOCOVISOL_PREPAGO_CONSUMOSCOVISOL_PRE { get; set; }
        public Nullable<decimal> C8_GC_TRANSITOGENERALESSPREPAGO_3_ND_SALDOCOVISUR_PREPAGO_CONSUMOSCOVISUR_PRE { get; set; }
        public Nullable<decimal> C8_GC_TRANSITOGENERALESSPREPAGO_3_ND_CONSUDETRACCOVIPERU_SUMADETRACCOVIPERU { get; set; }
        public Nullable<decimal> C8_GC_TRANSITOGENERALESSPREPAGO_3_ND_CONSUDETRACCOVISO_SUMADETRACCOVISOL { get; set; }
        public Nullable<decimal> C8_GC_TRANSITOGENERALESSPREPAGO_3_ND_CONSUDETRACCOVISUR_SUMADETRACCOVISUR { get; set; }
        public Nullable<decimal> C8_GC_TRANSITOSGENERALESPOSTPAGO_3_ND_CONSUMOSCOVIPERU_POST_SUMADECONSUMOCOVIPER { get; set; }
        public Nullable<decimal> C8_GC_TRANSITOSGENERALESPOSTPAGO_3_ND_CONSUMOSCOVISOL_POST_SUMADECONSUMOCOVISOL { get; set; }
        public Nullable<decimal> C8_GC_TRANSITOSGENERALESPOSTPAGO_3_ND_CONSUMOSCOVISUR_POST_SUMADECONSUMOCOVISUR { get; set; }
        public Nullable<decimal> C8_GC_TRANSITOSGENERALESPOSTPAGO_3_ND_DETRACCOVIPERU_POST_SUMADETRACCOVIPERU { get; set; }
        public Nullable<decimal> C8_GC_TRANSITOSGENERALESPOSTPAGO_3_ND_DETRACCOVISOL_POST_SUMADETRACCOVISOL { get; set; }
        public Nullable<decimal> C8_GC_TRANSITOSGENERALESPOSTPAGO_3_ND_DETRACCOVISUR_POST_SUMADETRACCOVISUR { get; set; }
        public Nullable<System.DateTime> C3_FE_FECHA_INICIO { get; set; }
        public Nullable<System.DateTime> C3_PR1_FE_FECHA_EMISION_COMPROBANTE { get; set; }
        public Nullable<int> C3_SS_TIPO_OPERACION { get; set; }
    }
}
