//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXCEL2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Panel_1008
    {
        public int ID { get; set; }
        public Nullable<int> C_ElementID { get; set; }
        public Nullable<System.DateTime> Creado { get; set; }
        public Nullable<int> IdCreador { get; set; }
        public Nullable<int> TipoCreador { get; set; }
        public Nullable<System.DateTime> Modificado { get; set; }
        public Nullable<int> IdModificador { get; set; }
        public Nullable<int> TipoModificador { get; set; }
        public string C_List_of_Process_References { get; set; }
        public string C_List_of_Process_Themes { get; set; }
        public Nullable<int> C8_A__PR3_LIQUIDACION_RESUMEN_DETALL_3_TL_CANTIDAD_LIQ_Total_Cantidad { get; set; }
        public Nullable<decimal> C8_A__PR3_LIQUIDACION_RESUMEN_DETALL_3_TL_MONTO_LIQ_Total_Monto { get; set; }
        public Nullable<decimal> C8_A__PR3_REPORTE_FINAL_FACTURACION_3_TL_TOTAL_VENTA_Total_Venta { get; set; }
        public Nullable<int> C8_A__PR3_LIQUIDACION_TRANSITOS_3_TL_PLACA_LIQ_Total_cantidad { get; set; }
        public Nullable<decimal> C3_A__PR3_TOTAL_TRANSFERIDO { get; set; }
        public Nullable<decimal> C8_A__PR3_OTROS_DESCUENTOS_3_T_MONTO_Total_monto { get; set; }
        public string C3_A__PR3_REFERENCIA { get; set; }
        public Nullable<int> C3_A__PR3_CONCESIONARIA { get; set; }
        public string C3_A__PR3_ASUNTO1 { get; set; }
        public Nullable<int> C3_A__PR3_CANT_RECORDATORIO { get; set; }
        public Nullable<decimal> C8_A__PR3_ABONO_TRANSITO_3_T_MONTO_BONO_T_Sumatoria { get; set; }
        public Nullable<System.DateTime> C8_A__PR3_ABONO_TRANSITO_3_T_FECHA_Fecha_tranfs_min { get; set; }
        public Nullable<decimal> C8_A__PR3_ABONO_DETRACCION_3_PR3_MONTO_Sumatoria { get; set; }
        public Nullable<System.DateTime> C8_A__PR3_ABONO_DETRACCION_3_PR3_FECHA_DET_Fecha_tranfs_min { get; set; }
        public Nullable<bool> C3_A__PR3_TRANSFERENCIA_OBS { get; set; }
        public Nullable<int> C3_A__PR3_ESTADO_PROCESO { get; set; }
        public Nullable<decimal> C3_A__PR3_MONTO_DIFERENCIA_TRANS { get; set; }
        public Nullable<System.DateTime> C3_A__PR3_FS_FECHA_FIN { get; set; }
        public Nullable<System.DateTime> C3_A__PR3_FS_F_FECHA_INICIO_PROCESO { get; set; }
        public Nullable<System.DateTime> C3_A__PR3_FS_FECHA_INICIO { get; set; }
        public Nullable<bool> C3_A__PR3_FS_QUINCENA { get; set; }
        public Nullable<decimal> C3_A__PR3_TARIFA_TRANSITO_TER { get; set; }
        public string C3_A__PR3_OBSERVACION { get; set; }
        public Nullable<decimal> C3_A__PR3_MONTO_TOTAL { get; set; }
        public Nullable<decimal> C3_A__PR3_MONTO_DETRACCIONES { get; set; }
        public Nullable<decimal> C3_A__PR3_MONTO_TRANSITO { get; set; }
        public Nullable<decimal> C3_A__PR3_MONTO_VISA { get; set; }
        public Nullable<bool> C3_A__PR3_VALIDAR { get; set; }
        public string C3_PR3_REFERENCIA_PR1 { get; set; }
        public Nullable<int> C2_A__PR_CONCESIONARIAS_Id_ { get; set; }
        public string C2_A__PR_CONCESIONARIAS_A__TL_CODIGO_CONCESIONARIA { get; set; }
        public string C2_A__PR_CONCESIONARIAS__Nm_CONCESIONARIAS { get; set; }
        public Nullable<decimal> C8_A__GC_COMPROBANTES_TRANSITOS_3_ND_DETRACCION_TOTAL_RT_ND_TOTAL_DETRACCION { get; set; }
        public Nullable<decimal> C8_A__GC_COMPROBANTES_TRANSITOS_3_ND_PEAJE_TOTAL_RT_ND_TOTAL_PEAJE { get; set; }
        public Nullable<int> C8_A__GC_COMPROBANTES_TRANSITOS_0_AFECTA_DETRACCION_3_TL_CUENTA_RT_Cantidad { get; set; }
        public Nullable<decimal> C3_PR3_TOTAL_RETENCIONES { get; set; }
        public string C2_A__PR_CONCESIONARIAS_PR3_F_CUENTA_BANCARIA { get; set; }
        public string C3_PR3_ASUNTO2 { get; set; }
        public Nullable<int> C8_A__GC_COMPROBANTES_TRANSITOS_0_AFECTA_DETRACCION_3_TL_PR3_OBSERVACION_Cant_Observado { get; set; }
        public string C2_A__PR_CONCESIONARIAS_A__F_CON_CORREO { get; set; }
        public Nullable<decimal> C8_PR3_GC_OTROS_DESCUENTOS_DETRAC_3_T_MONTO_DET_Total_monto { get; set; }
        public Nullable<decimal> C3_PR3_MONTO_DIFERENCIA_DET { get; set; }
        public Nullable<decimal> C3_PR3_TOTAL_DESCUENTOS_TRANS { get; set; }
        public Nullable<decimal> C3_PR3_TOTAL_DESCUENTO_DET { get; set; }
        public Nullable<int> C8_A__GC_COMPROBANTES_TRANSITOS_0_AFECTA_DETRACCION_OBS_3_TL_PR3_OBSERVACION_Cant_Observado { get; set; }
        public Nullable<decimal> C8_PR3_GC_OTROS_DESCUENTOS_VISA_3_T_MONTO_VISA_Total_monto { get; set; }
        public Nullable<decimal> C3_PR3_TOTAL_DESCUENTOS_VISA { get; set; }
        public string C3_PR3_OBSERVACION2 { get; set; }
        public string C3_PR3_OBSERVACION4 { get; set; }
        public string C3_PR3_OBSERVACION3 { get; set; }
        public Nullable<bool> C3_PR3_ENVIO_RETENCION_MENSUAL { get; set; }
        public Nullable<bool> C3_PR3_ENVIO_DET_BUSES_MENSUAL { get; set; }
        public Nullable<bool> C3_PR3_DESCONTAR_TRANSITO { get; set; }
        public Nullable<decimal> C3_PR3_IMPORTE_DETRACCION_BUSES { get; set; }
        public Nullable<int> C3_PR3_PESTAÑA { get; set; }
        public Nullable<int> C2_PR3_PRE_TARIFA_TERR_Id_ { get; set; }
        public Nullable<decimal> C2_PR3_PRE_TARIFA_TERR_F_TAG_IGV { get; set; }
        public string C2_PR3_CO_PR3_TEXTO { get; set; }
        public Nullable<int> C2_PR3_CO_Id_ { get; set; }
        public Nullable<int> C2_PR3_CORREO_JEFE_VENTA_Id_ { get; set; }
        public string C2_PR3_CORREO_JEFE_VENTA_PR3_TEXTO { get; set; }
        public Nullable<int> C8_GC_COMPROBANTES_TRANSITOS_0_AFECTA_DETRACCION_3_TL_CUENTA_RT_Cantidad { get; set; }
        public Nullable<int> C8_GC_COMPROBANTES_TRANSITOS_3_TL_CUENTA_RT_Cantidad { get; set; }
        public Nullable<decimal> C8_GC_COMPROBANTES_TRANSITOS_3_ND_DETRACCION_TOTAL_RT_ND_TOTAL_DETRACCION { get; set; }
        public Nullable<decimal> C8_GC_COMPROBANTES_TRANSITOS_3_ND_PEAJE_TOTAL_RT_ND_TOTAL_PEAJE { get; set; }
        public Nullable<int> C8_GC_COMPROBANTES_TRANSITOS_0_AFECTA_DETRACCION_3_TL_PR3_OBSERVACION_Y_Cant_observado { get; set; }
        public Nullable<int> C8_GC_COMPROBANTES_TRANSITOS_0_AFECTA_DETRACCION_OBS_3_TL_PR3_OBSERVACION_Y_Cant_observado { get; set; }
        public string C2_PR_CONCESIONARIAS__Nm_CONCESIONARIAS { get; set; }
        public Nullable<int> C2_PR_CONCESIONARIAS_Id_ { get; set; }
        public string C2_PR_CONCESIONARIAS_TL_CODIGO_CONCESIONARIA { get; set; }
        public string C2_PR_CONCESIONARIAS_F_CON_CORREO { get; set; }
        public string C2_PR_CONCESIONARIAS_PR3_F_CUENTA_BANCARIA { get; set; }
        public Nullable<int> C3_PR3_ID_PANEL { get; set; }
        public Nullable<decimal> C8_A__PR3_LIQUIDACION_RESUMEN_3_T_Monto_Resumen_Suma_monto { get; set; }
        public Nullable<decimal> C3_PR3_COM_PA_RECAUDACION { get; set; }
        public Nullable<System.DateTime> C3_PR3_FECH_TRANSFERENCIA_TRANS { get; set; }
        public Nullable<System.DateTime> C3_PR3_FECH_TRANSFERENCIA_DET { get; set; }
        public Nullable<int> C3_PR3_EN_AÑO { get; set; }
        public string C3_PR3_COM_MES_TEXTO { get; set; }
        public string C3_PR3_TEMA1 { get; set; }
        public string C3_PR3_TEMA2 { get; set; }
        public Nullable<int> C3_PR3_ITEM_TRANSFERENCIA { get; set; }
        public Nullable<decimal> C3_PR3_REGULARIZAR_OTROS_DESCUENTOS { get; set; }
        public Nullable<decimal> C3_PR3_REGULARIZAR_MONTO { get; set; }
        public Nullable<int> C3_PR3_REGULARIZAR_MES { get; set; }
        public Nullable<int> C3_PR3_REGULARIZAR_AÑO { get; set; }
        public Nullable<int> C3_PR3_NUEVO_EXCEL { get; set; }
        public Nullable<int> C3_PR3_EN_AÑO_ANTERIOR { get; set; }
        public Nullable<int> C3_PR3_EN_AÑO_POSTERIOR { get; set; }
        public string C3_PR3_FAM_TEXTO_AÑO { get; set; }
        public Nullable<int> C8_A__PR3_TRANSITO_TERRAPUERTO_3_TL_PLACA_TERR_Total_Cantidad { get; set; }
        public Nullable<decimal> C3_PR3_REGULARIZAR_OTROS_DESCUENTOS_DET { get; set; }
        public Nullable<int> C2_PR3_CORREO_COPIA_Id_ { get; set; }
        public string C2_PR3_CORREO_COPIA_PR3_TEXTO { get; set; }
        public Nullable<decimal> C3_PR3_DESC_SIN_RETENCION { get; set; }
        public Nullable<decimal> C3_PR3_DET_COB_MES_ANT { get; set; }
        public Nullable<decimal> C3_PR3_DET_COB_MONTO { get; set; }
        public Nullable<decimal> C3_PR3_DET_COB_TOTAL { get; set; }
        public Nullable<decimal> C3_PR3_TRAN_COB_MES_ANT { get; set; }
        public Nullable<decimal> C3_PR3_TRAN_COB_MONTO { get; set; }
        public Nullable<decimal> C3_PR3_VISA_COB_MES_ANT { get; set; }
        public Nullable<decimal> C3_PR3_TRAN_COB_TOTAL { get; set; }
        public Nullable<decimal> C3_PR3_VISA_COB_MONTO { get; set; }
        public Nullable<decimal> C3_PR3_VISA_COB_TOTAL { get; set; }
        public Nullable<decimal> C8_PR3_COB_DESCUENTO_VISA_3_Monto_VISA_Suma { get; set; }
        public Nullable<decimal> C8_PR3_COB_DESCUENTO_TRAN_3_Monto_Suma { get; set; }
        public Nullable<decimal> C8_PR3_COB_DESCUENTO_DET_3_Monto_DET_Suma { get; set; }
        public Nullable<int> C3_PR3_F_ESTADO_FAM { get; set; }
        public string C3_PR3_OBSERVACION5 { get; set; }
        public Nullable<decimal> C3_PR3_RET_RETENCIONES { get; set; }
        public Nullable<decimal> C8_PR3_DETRACCIONES_3_TL_MONTO_DETRACION_Monto_total { get; set; }
        public Nullable<decimal> C8_PR3_RETENCION_MENSUAL_CONCESIO_3_TL_IMPORTE_Suma_total { get; set; }
        public Nullable<int> C3_PR3_TIPO_DESCUENTO { get; set; }
        public Nullable<decimal> C3_PR3_DIF_DETRACCION_BUSES { get; set; }
        public Nullable<decimal> C3_PR3_REGULARIZAR_OTROS_DESCUENTOS_VISA { get; set; }
        public Nullable<decimal> C8_PR3_DETRACCIONES_PENDIENTES_3_Detracción_Suma { get; set; }
        public Nullable<int> C8_PR3_DETRACCIONES_PENDIENTES_3_Tránsito_Cantidad { get; set; }
        public Nullable<int> C3_PR3_INDICADOR1 { get; set; }
        public Nullable<int> C3_PR3_INDICADOR5 { get; set; }
        public Nullable<int> C3_PR3_INDICADOR4 { get; set; }
        public Nullable<int> C3_PR3_INDICADOR3 { get; set; }
        public Nullable<int> C3_PR3_INDICADOR2 { get; set; }
        public Nullable<decimal> C8_PR3_AUTODETRACCIONES_3_PR3_MONTO_DEPOSITO_AUTO_Suma { get; set; }
        public Nullable<decimal> C8_GC_COMPROBANTES_TRANSITOS_0_AFECTA_DETRACCION_3_TL_MONTO_DETRACCION_CARGA_Y_Suma { get; set; }
        public Nullable<int> C8_PR3_AUTODETRACCIONES_3_TL_CORRELATIVO_AUTO_Cantidad { get; set; }
        public Nullable<System.DateTime> C3_PR3_FECH_TRANSFERENCIA_VISA { get; set; }
        public Nullable<decimal> C3_PR3_REGULARIZAR_AÑO_VISA { get; set; }
        public Nullable<decimal> C3_PR3_REGULARIZAR_MES_VISA { get; set; }
        public Nullable<decimal> C3_PR3_REGULARIZAR_MONTO_VISA { get; set; }
        public Nullable<decimal> C3_PR3_DIF3 { get; set; }
        public Nullable<decimal> C3_PR3_DIF2 { get; set; }
        public Nullable<decimal> C3_PR3_DIF1 { get; set; }
        public Nullable<decimal> C3_PR3_DIF6 { get; set; }
        public Nullable<decimal> C3_PR3_DIF5 { get; set; }
        public Nullable<decimal> C3_PR3_DIF4 { get; set; }
    }
}
