//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXCEL2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Panel_1008_4700
    {
        public int ID { get; set; }
        public Nullable<int> C_ElementID { get; set; }
        public Nullable<System.DateTime> Creado { get; set; }
        public Nullable<int> IdCreador { get; set; }
        public Nullable<int> TipoCreador { get; set; }
        public Nullable<System.DateTime> Modificado { get; set; }
        public Nullable<int> IdModificador { get; set; }
        public Nullable<int> TipoModificador { get; set; }
        public Nullable<int> C_ExecutedScript { get; set; }
        public Nullable<int> C_Register_creation_ProcessID { get; set; }
        public Nullable<int> C_Origin_Register_ID { get; set; }
        public Nullable<int> C_RegisterStatus { get; set; }
        public Nullable<int> C_Register_Origin_ID { get; set; }
        public Nullable<int> C_Register_Origin_Type { get; set; }
        public Nullable<int> C_Numerator { get; set; }
        public Nullable<System.DateTime> C3_FE_FECHA_COMPROBANTE_RT { get; set; }
        public string C3_TL_CUENTA_RT { get; set; }
        public string C3_TL_NOMBRE_CLIENTE_RT { get; set; }
        public string C3_TL_RUC_CLIENTE_RT { get; set; }
        public string C3_TL_TIPO_COMPROBANTE_RT { get; set; }
        public string C3_TL_NRO_COMPROBANTE_RT { get; set; }
        public Nullable<decimal> C3_ND_PEAJE_TOTAL_RT { get; set; }
        public Nullable<decimal> C3_ND_DETRACCION_TOTAL_RT { get; set; }
        public string C3_TL_CONCAT_RT { get; set; }
        public string C3_TL_SERIE_RT { get; set; }
        public string C3_TL_CORRELATIVO_RT { get; set; }
        public Nullable<int> C3_TL_CONCESIONARIA { get; set; }
        public Nullable<System.DateTime> C3_TL_FECHA_TRANSFERENCIA_Y { get; set; }
        public string C3_TL_NUM_DETRACCION_CARGA_Y { get; set; }
        public Nullable<decimal> C3_TL_MONTO_DETRACCION_CARGA_Y { get; set; }
        public Nullable<int> C3_TL_PR3_OBSERVACION_Y { get; set; }
        public string C3_TL_DETALLE2_Y { get; set; }
        public Nullable<System.DateTime> C3_TL_FECHA_PAGO_DETRACCION_CAR_Y { get; set; }
    }
}
