//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXCEL2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Panel_1009_4916
    {
        public int ID { get; set; }
        public Nullable<int> C_ElementID { get; set; }
        public Nullable<System.DateTime> Creado { get; set; }
        public Nullable<int> IdCreador { get; set; }
        public Nullable<int> TipoCreador { get; set; }
        public Nullable<System.DateTime> Modificado { get; set; }
        public Nullable<int> IdModificador { get; set; }
        public Nullable<int> TipoModificador { get; set; }
        public Nullable<int> C_ExecutedScript { get; set; }
        public Nullable<int> C_Register_creation_ProcessID { get; set; }
        public Nullable<int> C_Origin_Register_ID { get; set; }
        public Nullable<int> C_RegisterStatus { get; set; }
        public Nullable<int> C_Register_Origin_ID { get; set; }
        public Nullable<int> C_Register_Origin_Type { get; set; }
        public Nullable<int> C_Numerator { get; set; }
        public string C3_TL_RUC_CLIENTE_CP { get; set; }
        public string C3_TL_NOMBRE_CLIENTE_CP { get; set; }
        public string C3_TL_TIPO_DOCUMENTO_CP { get; set; }
        public string C3_TL_NRO_COMPROBANTE_CP { get; set; }
        public string C3_TL_MONEDA_CP { get; set; }
        public Nullable<decimal> C3_ND_IMPORTE_TOTAL_CP { get; set; }
        public string C3_TL_IMPORTE_TOTAL_CP { get; set; }
        public Nullable<System.DateTime> C3_FE_FECHA_EMISION_CP { get; set; }
        public string C3_TL_ESTADO_DOC_TRIBUTARIO_CP { get; set; }
        public string C3_TL_DOCUMENTO_REFERENCIA_CP { get; set; }
        public string C3_TL_CONCESIONARIA_CP { get; set; }
        public string C3_TL_CUENTA_CP { get; set; }
        public string C3_TL_DETRACCION_TOTAL_CP { get; set; }
        public Nullable<decimal> C3_ND_DETRACCION_TOTAL_CP { get; set; }
        public string C3_TL_CONCAT_CP { get; set; }
        public Nullable<int> C3_SS_OBSERVACION_CP { get; set; }
        public string C3_TM_DETALLE { get; set; }
        public string C3_TL_ORDEN_COMPRA { get; set; }
        public string C3_TL_OP_GRAVADA { get; set; }
        public string C3_TL_OP_NO_GRAVADA { get; set; }
        public string C3_TL_IGV_CP { get; set; }
        public string C3_TL_OTROS_IMPUESTOS { get; set; }
        public string C3_TL_OTROS_CARGOS { get; set; }
        public Nullable<System.DateTime> C3_F_FECHA_VENCIMIENTO { get; set; }
        public string C3_TL_ESTADO_DOC { get; set; }
        public string C3_TL_OBSERVACION_SUNAT { get; set; }
        public string C3_TL_HABILITADO { get; set; }
        public string C3_TL_TIPO_EMISION { get; set; }
        public string C3_TL_OBSERVACIONES { get; set; }
        public string C3_FE_FECHA_EMISION_CP_TEXTO { get; set; }
        public string C3_F_FECHA_VENCIMIENTO_TEXTO { get; set; }
        public string C3_F_ENVIADO_DECLARAR_TEXTO { get; set; }
        public Nullable<System.DateTime> C3_F_ENVIADO_DECLARAR { get; set; }
        public string C3_TL_SERIE { get; set; }
        public string C3_TL_CORRELATIVO { get; set; }
    }
}
