//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXCEL2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Panel_5
    {
        public int ID { get; set; }
        public Nullable<int> C_ElementID { get; set; }
        public Nullable<System.DateTime> Creado { get; set; }
        public Nullable<int> IdCreador { get; set; }
        public Nullable<int> TipoCreador { get; set; }
        public Nullable<System.DateTime> Modificado { get; set; }
        public Nullable<int> IdModificador { get; set; }
        public Nullable<int> TipoModificador { get; set; }
        public string C_List_of_Process_References { get; set; }
        public string C_List_of_Process_Themes { get; set; }
        public Nullable<decimal> C3_PR3_TAG_CALCULO { get; set; }
        public Nullable<int> C3_PR3_TAG_CANTIDAD { get; set; }
        public Nullable<decimal> C3_PR3_TAG_COSTO { get; set; }
        public Nullable<System.DateTime> C3_PR3_TAG_FECHA_INICIO { get; set; }
        public Nullable<decimal> C3_PR3_TAG_IGV { get; set; }
        public Nullable<int> C3_PR3_TAG_MES { get; set; }
        public string C3_PR3_TAG_REFERENCIA { get; set; }
        public Nullable<int> C3_PR3_TAG_ESTADO { get; set; }
        public string C3_PR3_TAG_AÑO { get; set; }
        public string C3_PR3_TAG_ASUNTO { get; set; }
        public string C3_PR3_TAG_CORREO_CON { get; set; }
        public string C3_F_TAG_CORREO_PUNTO { get; set; }
        public Nullable<decimal> C3_PR3_TAG_VALOR_UNITARIO { get; set; }
        public Nullable<int> C3_PR3_TAG_CANTIDAD1 { get; set; }
        public string C3_F_TAG_CORREO_PUNTO1 { get; set; }
        public Nullable<int> C3_PR3_TAG_CORRELATIVO { get; set; }
        public Nullable<int> C3_PR3_TAG_ID_PANEL { get; set; }
        public Nullable<int> C3_PR3_TAG_CORRELATIVO_FACTURA { get; set; }
        public string C3_PR3_LINK_BOLETA { get; set; }
        public string C3_PR3_LINK_FACTURA { get; set; }
        public string C3_PR3_TAG_MES_TEXTO { get; set; }
        public Nullable<bool> C3_PR3_FACTURA_FACELE { get; set; }
        public Nullable<int> C3_PR3_TAG_ESTADO_COVIPERU { get; set; }
        public string C3_PR3_ASUNTO2 { get; set; }
        public Nullable<bool> C3_PR3_FACTURA_FACELE_COVIPERU { get; set; }
        public string C3_PR3_TM_BOLETA { get; set; }
        public string C3_PR3_TM_FACTURA { get; set; }
        public string C3_PR3_T_SERIE_FACTURA { get; set; }
        public string C3_PR3_T_SERIE_BOLETA { get; set; }
        public string C3_PR3_LINK_CDR { get; set; }
        public string C3_PR3_LINK_XML { get; set; }
        public string C3_PR3_LINK_PDF { get; set; }
        public Nullable<int> C3_PR3_WS_WINDOWS_CORRELATIVO { get; set; }
    }
}
