//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXCEL2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Panel_1009
    {
        public int ID { get; set; }
        public Nullable<int> C_ElementID { get; set; }
        public Nullable<System.DateTime> Creado { get; set; }
        public Nullable<int> IdCreador { get; set; }
        public Nullable<int> TipoCreador { get; set; }
        public Nullable<System.DateTime> Modificado { get; set; }
        public Nullable<int> IdModificador { get; set; }
        public Nullable<int> TipoModificador { get; set; }
        public string C_List_of_Process_References { get; set; }
        public string C_List_of_Process_Themes { get; set; }
        public Nullable<System.DateTime> C3_A__PR3_FS_FECHA_FIN { get; set; }
        public Nullable<System.DateTime> C3_A__PR3_FS_FECHA_INICIO { get; set; }
        public Nullable<bool> C3_A__PR3_FS_QUINCENA { get; set; }
        public string C3_A__PR3_REFERENCIA { get; set; }
        public Nullable<int> C3_A__PR3_CONCESIONARIA { get; set; }
        public Nullable<System.DateTime> C3_A__PR3_FS_F_FECHA_INICIO_PROCESO { get; set; }
        public Nullable<bool> C3_A__PR3_VALIDAR { get; set; }
        public string C2_PR_CONCESIONARIAS__Nm_CONCESIONARIAS { get; set; }
        public string C2_PR_CONCESIONARIAS_F_CON_CORREO { get; set; }
        public Nullable<int> C2_PR_CONCESIONARIAS_Id_ { get; set; }
        public string C2_PR_CONCESIONARIAS_PR3_F_CUENTA_BANCARIA { get; set; }
        public string C2_PR_CONCESIONARIAS_TL_CODIGO_CONCESIONARIA { get; set; }
        public Nullable<int> C3_PR3_COM_MES { get; set; }
        public string C3_PR3_TAG_AÑO { get; set; }
        public Nullable<int> C3_NE_CONTADOR { get; set; }
        public string C3_PR3_REFERENCIA_PR1 { get; set; }
        public Nullable<int> C3_PR3_CANT_OBS_RESUMEN { get; set; }
        public Nullable<int> C3_PR3_CANT_OBS_CP { get; set; }
        public Nullable<int> C3_PR3_SS_ACCION { get; set; }
        public Nullable<int> C3_PR3_EN_AÑO { get; set; }
        public string C3_TM_OBSERVACION { get; set; }
        public Nullable<decimal> C8_GC_COMPROBANTES_TRANSITOS_3_ND_PEAJE_TOTAL_RT_ND_TOTAL_PEAJE { get; set; }
        public Nullable<decimal> C8_GC_COMPROBANTES_PAGO_3_ND_IMPORTE_TOTAL_CP_SUM_IMPORTE { get; set; }
        public Nullable<decimal> C3_PR3_COM_PP_VALOR_COMISION { get; set; }
        public Nullable<decimal> C3_PR3_COM_PP_TRANSITO_SIN_IGV { get; set; }
        public Nullable<decimal> C3_PR3_COM_PP_TOTAL_COMISION { get; set; }
        public Nullable<decimal> C3_PR3_COM_PP_RECAUDACION { get; set; }
        public Nullable<decimal> C3_PR3_COM_PP_MONTO_COMISION { get; set; }
        public Nullable<decimal> C3_PR3_COM_PP_IGV { get; set; }
        public Nullable<decimal> C3_PR3_COM_PP_FIN_TOTAL_COMISION { get; set; }
        public Nullable<decimal> C3_PR3_COM_PP_FIN_MONTO_COMISION { get; set; }
        public Nullable<decimal> C3_PR3_COM_PP_FIN_IGV { get; set; }
        public Nullable<decimal> C3_PR3_COM_PP_AJUSTE_MONTO_COMISION { get; set; }
        public Nullable<decimal> C3_PR3_COM_PP_AJUSTE_IGV { get; set; }
        public Nullable<decimal> C3_PR3_COM_PA_VALOR_COMISION { get; set; }
        public Nullable<decimal> C3_PR3_COM_PA_TRANSITO_SIN_IGV { get; set; }
        public Nullable<decimal> C3_PR3_COM_PA_TOTAL_COMISION { get; set; }
        public Nullable<decimal> C3_PR3_COM_PA_RECAUDACION { get; set; }
        public Nullable<decimal> C3_PR3_COM_PA_MONTO_COMISION { get; set; }
        public Nullable<decimal> C3_PR3_COM_PA_IGV { get; set; }
        public Nullable<decimal> C3_PR3_COM_PA_FIN_TOTAL_COMISION { get; set; }
        public Nullable<decimal> C3_PR3_COM_PA_FIN_MONTO_COMISION { get; set; }
        public Nullable<decimal> C3_PR3_COM_PA_FIN_IGV { get; set; }
        public Nullable<decimal> C3_PR3_COM_FP_TRANSITO_SIN_IGV { get; set; }
        public Nullable<decimal> C3_PR3_COM_FP_TOTAL_COMISION { get; set; }
        public Nullable<decimal> C3_PR3_COM_FP_RECAUDACION { get; set; }
        public Nullable<decimal> C3_PR3_COM_FP_IGV { get; set; }
        public Nullable<decimal> C3_PR3_COM_FP_MONTO_COMISION { get; set; }
        public Nullable<decimal> C3_PR3_COM_FP_DIF_TRANSITO_SIN_IGV { get; set; }
        public Nullable<decimal> C3_PR3_COM_FP_DIF_TOTAL_COMISION { get; set; }
        public Nullable<decimal> C3_PR3_COM_FP_DIF_MONTO_COMISION { get; set; }
        public Nullable<decimal> C3_PR3_COM_FP_DIF_IGV { get; set; }
        public Nullable<decimal> C3_PR3_COM_FA_TRANSITO_SIN_IGV { get; set; }
        public Nullable<decimal> C3_PR3_COM_FA_TOTAL_COMISION { get; set; }
        public Nullable<decimal> C3_PR3_COM_FA_RECAUDACION { get; set; }
        public Nullable<decimal> C3_PR3_COM_FA_MONTO_COMISION { get; set; }
        public Nullable<decimal> C3_PR3_COM_FA_IGV { get; set; }
        public Nullable<decimal> C3_PR3_COM_FA_DIF_TRANSITO_SIN_IGV { get; set; }
        public Nullable<decimal> C3_PR3_COM_FA_DIF_TOTAL_COMISION { get; set; }
        public Nullable<decimal> C3_PR3_COM_FA_DIF_MONTO_COMISION { get; set; }
        public Nullable<decimal> C3_PR3_COM_FA_DIF_IGV { get; set; }
        public Nullable<int> C3_PR3_COM_CONTADOR { get; set; }
        public Nullable<int> C2_PR3_CO_Id_ { get; set; }
        public Nullable<int> C2_A__PR3_CO_Id_ { get; set; }
        public string C2_PR3_CO_PR3_TEXTO { get; set; }
        public string C2_PR3_CORREO_JEFE_VENTA_PR3_TEXTO { get; set; }
        public Nullable<int> C2_PR3_CORREO_JEFE_VENTA_Id_ { get; set; }
        public string C3_PR3_ASUNTO1 { get; set; }
        public string C3_PR3_COM_RES_DIFERENCIA { get; set; }
        public string C3_PR3_DIF_MES_AJUSTE { get; set; }
        public Nullable<int> C3_PR3_DIF_AÑO_AJUSTE { get; set; }
        public string C3_PR3_COM_MES_TEXTO { get; set; }
        public Nullable<System.DateTime> C3_PR3_FE_FECHA_COM_FINAL { get; set; }
        public Nullable<System.DateTime> C3_PR3_FE_FECHA_COM_FINAL_AJUSTE { get; set; }
        public Nullable<decimal> C3_PR3_COM_FINAL_DIFERENCIA { get; set; }
        public Nullable<decimal> C3_PR3_COM_FINAL_DIFERENCIA_AJUSTE { get; set; }
        public Nullable<decimal> C3_PR3_COM_POR_TRANSFERIR { get; set; }
        public Nullable<decimal> C3_PR3_COM_POR_TRANSFERIR_DET { get; set; }
        public Nullable<decimal> C8_GC_COMPROBANTES_TRANSITOS_3_ND_DETRACCION_TOTAL_RT_ND_TOTAL_DETRACCION { get; set; }
        public Nullable<int> C3_3_PR3_COM_CONTADOR_TER { get; set; }
        public Nullable<int> C3_PR3_COM_ESTADO { get; set; }
        public Nullable<int> C3_PR3_COM_PP_AÑO_AJUSTE { get; set; }
        public string C3_PR3_COM_PP_MES_AJUSTE { get; set; }
        public Nullable<int> C3_PR3_ID_PANEL { get; set; }
        public string C3_PR3_TEMA1 { get; set; }
        public string C3_PR3_TEMA2 { get; set; }
        public Nullable<int> C3_PR3_MES_TRANSFERENCIA { get; set; }
        public Nullable<int> C3_PR3_CANT_RECORDATORIO { get; set; }
        public Nullable<int> C3_PR3_COM_POR_TRANSFERIR_SN { get; set; }
    }
}
