//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXCEL2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Panel_2013_8925
    {
        public int ID { get; set; }
        public Nullable<int> C_ElementID { get; set; }
        public Nullable<System.DateTime> Creado { get; set; }
        public Nullable<int> IdCreador { get; set; }
        public Nullable<int> TipoCreador { get; set; }
        public Nullable<System.DateTime> Modificado { get; set; }
        public Nullable<int> IdModificador { get; set; }
        public Nullable<int> TipoModificador { get; set; }
        public Nullable<int> C_ExecutedScript { get; set; }
        public Nullable<int> C_Register_creation_ProcessID { get; set; }
        public Nullable<int> C_Origin_Register_ID { get; set; }
        public Nullable<int> C_RegisterStatus { get; set; }
        public Nullable<int> C_Register_Origin_ID { get; set; }
        public Nullable<int> C_Register_Origin_Type { get; set; }
        public Nullable<int> C_Numerator { get; set; }
        public Nullable<System.DateTime> C3_PRE_FECHARECARGA { get; set; }
        public Nullable<decimal> C3_PRE_MONTORECARGA { get; set; }
        public string C3_PRE_TL_RECIBO { get; set; }
        public Nullable<decimal> C3_PRE_MONTODETRACCION { get; set; }
        public string C3_PRE_RECIBODETRACCION { get; set; }
        public string C3_PRE_CUENTA_IDENTIFICADOR { get; set; }
    }
}
